[package]
name = "the_strats"
version = "0.1.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]
edition = "2018"

[dependencies]
gdnative = "*"
specs = "*"
crossbeam = "*"

[features]
default = ["specs/shred-derive"]

[lib]
crate-type = ["cdylib"]